### ISSUE TITLE
A number of WIDGET_DRAW (button event) problems.

### ISSUE THREAD

**Issue by jtappin** [gnudatalanguage/gdl#1162]
I'm not sure if any/all of these are known issues or not yet implemented, but there are a few issues I've found with button events on scrolled draw widgets.

The main one is that the event coordinates are always reported as if the viewport is over the top-left corner of the widget (i.e. the default position).

While trying to chase that into a corner, I also noticed that `widget_control, id, get_draw_view=pxy` always seems to return `[2,2]`, while the `set_draw_view` keyword is not implemented.

Finally, one not related to scrolling, the `modifiers` field of the event structure is always zero.

This quick code allows all of the above to be seen.
[coordinates.pro](https://github.com/gnudatalanguage/gdl/files/7347828/coordinates.txt)

**Comment by GillesDuvert** [comment]
hopefully solved in #1162, thanks!

**Comment by jtappin** [comment]
> hopefully solved in #1162, thanks!

That solves most of the issues, but the event coordinates are still wrong.

**Comment by GillesDuvert** [comment]
indeed.

**Comment by GillesDuvert** [comment]
solved in #1166
