### ISSUE TITLE
CONTOUR, /iso is broken when x < y

### ISSUE THREAD

**Issue by alaingdl** [gnudatalanguage/gdl#1495]
```
GDL> contour, dist(12,12),/iso    ; ok
GDL> contour, dist(102,12),/iso  ; ok
GDL> contour, dist(12,122),/iso   ; <<-- NOK
```

(this bug appeared between Sept 26 and Oct 18)

**Comment by GillesDuvert** [comment]
solved in #1515

**Comment by alaingdl** [comment]
See from here, on the current Git version including you changes, the current behavior of /iso is still not OK (but improved for the worse cases), eg :

(assuming `window, xsize=800, ysize=400`)

`contour, dist(120),/iso` is the same that `contour, dist(120),/iso`

All in my limited tests were perfect before Oct 18. (see from here in current statut, {x|y}style=1 seems to be not enforced too)

**Comment by GillesDuvert** [comment]
ah yes I see -- window aspect ratio not taken into account.
